#!/bin/sh

brew cask install font-wendy-one
brew cask install font-andale-mono
brew cask install font-cutive-mono
brew cask install font-dejavu-sans-mono-for-powerline
brew cask install font-droid-sans-mono
brew cask install font-droid-sans-mono-for-powerline
brew cask install font-everson-mono
brew cask install font-fantasque-sans-mono
brew cask install font-fira-mono
brew cask install font-fira-mono-for-powerline
brew cask install font-kawkab-mono
brew cask install font-liberation-mono-for-powerline
brew cask install font-monofett
brew cask install font-monofur
brew cask install font-monoid
brew cask install font-monoisome
brew cask install font-mononoki
brew cask install font-monoone
brew cask install font-monoton
brew cask install font-nova-mono
brew cask install font-oxygen-mono
brew cask install font-pt-mono
brew cask install font-roboto-mono
brew cask install font-roboto-mono-for-powerline
brew cask install font-share-tech-mono
brew cask install font-ubuntu-mono-powerline
brew cask install font-anonymous-pro-for-powerline
brew cask install font-consolas-for-powerline
brew cask install font-inconsolata-dz-for-powerline
brew cask install font-inconsolata-for-powerline
brew cask install font-inconsolata-g-for-powerline
brew cask install font-menlo-for-powerline
brew cask install font-meslo-lg-for-powerline
brew cask install font-sauce-code-powerline
brew cask install font-source-code-pro
brew cask install font-source-han-code-jp
brew cask install font-source-han-sans
brew cask install font-source-sans-pro
brew cask install font-source-serif-pro
brew cask install font-special-elite
brew cask install font-ubuntu
brew cask install font-underdog
brew cask install font-acme
brew cask install font-aileron
brew cask install font-awesome-terminal-fonts
brew cask install font-basic
brew cask install font-bigshot-one
brew cask install font-brawler
brew cask install font-bree-serif
brew cask install font-bubblegum-sans
brew cask install font-code
brew cask install font-code2000
brew cask install font-code2001
brew cask install font-code2002
brew cask install font-computer-modern
brew cask install font-corben
brew cask install font-devicons
brew cask install font-droid-sans
brew cask install font-droid-serif
brew cask install font-fira-code
brew cask install font-fira-sans
brew cask install font-fontawesome
brew cask install font-hack
brew cask install font-inconsolata
brew cask install font-ionicons
brew cask install font-material-icons
brew cask install font-materialdesignicons-webfont
brew cask install font-foundation-icons
brew cask install font-material-icons
brew cask install font-materialdesignicons-webfont
brew cask install font-octicons
brew cask install font-open-iconic
brew cask install font-webdings
brew cask install font-roboto
brew cask install font-roboto-condensed
brew cask install font-roboto-slab
brew cask install font-raleway
brew cask install font-oswald
brew cask install font-open-sans
brew cask install font-open-sans-condensed
brew cask install font-noto-serif
brew cask install font-noto-sans
brew cask install font-maven-pro
